across-protocol/indexer

- apps/node/README.md
- apps/node/package.json
- apps/node/src/app.ts
- packages/indexer-api/.mocharc.json
- packages/indexer-api/README.md
- packages/indexer-api/eslint.config.js
- packages/indexer-api/package.json
- packages/indexer-api/src/express-app.ts
- packages/indexer-api/src/index.ts
- packages/indexer-api/src/main.ts
- packages/indexer-api/src/services/example.test.ts
- packages/indexer-api/src/services/example.ts
- packages/indexer-api/src/services/index.ts
- packages/indexer-api/src/types.ts
- packages/indexer-api/tsconfig.json
- pnpm-lock.yaml
we need some pattern for exposing indexed data through a restful endpoint
adds a new package called indexer-api which is meant to be a pattern for exposing various indexed data. it offers a pattern for minimal boilerplate while staying pretty unopinionated on how you create your indexer.  You are only required to expose an express router and a path to that router, at which it can be automatlically added to the collection of indexed calls.  see readme for more details.
> feat: add indexer api boilerplate and example usage

- packages/indexer/src/main.ts
- packages/indexer/src/services/deposits.ts
we want to add hubpool client to the spoke pool clients
This adds a new env for hubpool provider, and changes the env names for spoke pool providers. we use this to instanciate both across config and hubpool client and update them before attempting to update spoke pool clients. 
- add in postgres persistence
- retry/cache rpc provider
> feat: add config and hub clients with updating

- turbo.json
The `outputs` key tells Turborepo files and directories it should cache when the task has successfully completed. The paths that are currently set in this list don't correspond to the output path of the `tsc` compiler.
After this change, if no package/app is changed, the build process consists of cache hits only, the build time being a matter of hundreds of milliseconds
> fix: fix build cache path

- packages/indexer/src/main.ts
- packages/indexer/src/redisCache.ts
- packages/indexer/src/services/deposits.ts
We want to make sure retry provider allows us to capture all the events without timeout errors, also retry provider was starting up with errors
Retry provider seems to solve the issue of timeouts on spokepool by setting maxconcurrency low, have only tested with a value of 1.  There were 2 fixes needed: one was with chain id not being passed into config, the other was with the redis cache not parsing json results.  There are other issues to do with caching the latest block for hubpool, but will address this in future pr
We need to make sure we arent caching block ranges for hubpool until corresponding spoke pool actually succeeds in updating the same range, its capture in this issue: https://linear.app/uma/issue/ACX-2597/improve-indexing
> fix(indexer): fix retry provider logic

- packages/indexer/src/main.ts
- packages/indexer/src/services/hubPoolIndexer.ts
- packages/indexer/src/services/index.ts
- packages/indexer/src/services/spokePoolIndexer.ts
- packages/indexer/src/utils.ts
Add hubpool indexer with block range success status in the same way as previous spoke pool indexer.
This adds hubpoolindexer file which is basically a copy of the spoke pool indexer file but for hub events.  also adds similar config and startup routine as the spoke pool indexer
future prs will update spoke pool indexer to catch up with what was done in services/deposits.ts and deal with situations where redis and postres are not synced correctly
> feat: add hubpool event saving with block range checks

- packages/indexer-database/src/entities/evm/ProposedRootBundle.ts
- packages/indexer-database/src/migrations/1726249543923-ProposedRootBundle.ts
- packages/indexer/src/services/hubPoolIndexer.ts
Adds an array of chain ids that represent the parallel array of `bundleEvaluationBlockNumbers`. The indices of both these columns are matched so `chainIds[0]` is the chain Id that represents the cutoff of `bundleEvaluationBlockNumbers[0]`
> feat(bundle): include chain ids in proposed bundle events

- docker/migrations.command.sh
fixing the issue
```
./docker/migrations.command.sh: cd: line 8: can't cd to ./packages/indexer-database: No such file or directory
npm error Missing script: "db:migration:run"
```
> Fix: Migration execution not found

- packages/indexer-database/src/entities/Bundle.ts
- packages/indexer-database/src/entities/BundleBlockRange.ts
- packages/indexer-database/src/entities/index.ts
- packages/indexer-database/src/main.ts
- packages/indexer-database/src/migrations/1726523435568-BundleBlockRange.ts
- packages/indexer/src/database/BundleRepository.ts
- packages/indexer/src/services/bundles.ts
We should track start/end block ranges into their own entity so that resolving a bundles range requires a single lookup.
> feat(bundles): add block range tracking

- packages/indexer-database/src/entities/RootBundleExecutedJoinTable.ts
Migrations dropping and recreating foreign keys for "bundle_executions" table are being created every time we generate migrations. This was happening because typeorm is keeping track of this table from two entities (Bundle and RootBundleExecutedJoinTable).
> fix: migrations issue

- packages/indexer/src/services/hubPoolIndexer.ts
- packages/indexer/src/services/spokePoolIndexer.ts
- packages/indexer/src/utils/contractUtils.ts
These functions can be synchronous because the contract clients accept `toBlock = undefined` and will resolve `toBlock = provider.getBlockNumber` for us.
> improve(utils): remove async requirement on  functions

- packages/indexer/src/main.ts
> nit: remove unused variable

- packages/indexer/src/database/BundleRepository.ts
- packages/indexer/src/services/bundles.ts
The `Executed` status of Bundles was not being set because when executing the following query Typeorm was converting `proposal.id` to `proposalId`.
```
const leafCountSubquery = `(SELECT proposal."poolRebalanceLeafCount"
FROM "evm"."proposed_root_bundle" proposal
WHERE proposal.id = bundle."proposalId"
LIMIT 1)`;
```
> fix(bundleProccesor): executed status query

- packages/indexer/src/services/HubPoolIndexerDataHandler.ts
- packages/indexer/src/services/SpokePoolIndexerDataHandler.ts
When setting the `from` block in the SDK contract clients, `firstBlockToSearch` is the correct property to set, not `eventSearchConfig.fromBlock`
> fix: set from block when updating sdk clients

- packages/indexer/package.json
- packages/indexer/src/utils/contractUtils.ts
- pnpm-lock.yaml
The spokePool address for Zora was incorrectly set in the version of the Across contracts package we were using. [See](https://github.com/across-protocol/contracts/pull/580)
In the latest version of the contracts package, getDeployedAddress may return undefined if the contract is not found, so we need to handle this case.
> fix: update across contracts

- packages/indexer/src/data-indexing/service/Indexer.ts
Because of the logic for getting the integrator id, we make many getTransactionHash calls (thousands per block range) which are taking a long time. Ideally the integrator id should be computed using the Redis queues.
> fix: temporarily reduce the size of the block range

- packages/indexer/src/services/SpokePoolIndexerDataHandler.ts
This PR removes the spokeClient instance that lives inside the SpokePoolIndexerDataHandler class, so it doesn't accumulate events anymore other than just those needed from the fetched block range
> fix: optimise spoke pool client usage

- packages/indexer-database/src/utils/BaseRepository.ts
This query was meant to delete events that were removed due to a re-org, but the query is wrong and it deletes more data than it should
> fix: remove the logic for deleting removed events

- packages/indexer-database/src/entities/Bundle.ts
- packages/indexer-database/src/entities/evm/ProposedRootBundle.ts
- packages/indexer-database/src/entities/evm/RootBundleCanceled.ts
- packages/indexer-database/src/entities/evm/RootBundleDisputed.ts
- packages/indexer/src/database/BundleRepository.ts
- packages/indexer/src/services/bundles.ts
This PR fixes two issues related to bundles:
- When saving the bundle range, we were not incrementing the start block so the end block of each bundle was being repeated as the start block of the next bundle.
- When relating events to bundles, we were assuming that the bundle id was equal to the id of the proposal, but that might not be true in some cases.
> fix(bundles): fix range start block and bundle id when assigning events

- packages/indexer/src/services/BundleBuilderService.ts
This PR updates the logic to avoid running the bundle builder when the database is too far behind the head block. The issue arises because the bundle builder sets the transient bundle’s end block to the current head. If we’re significantly behind, this can lead to memory errors as the system tries to load/store an excessive amount of data across all chains.
> improve: only run bundle builder when close to head

- packages/indexer/src/main.ts
- packages/indexer/src/redis/bundleLeavesCache.ts
- packages/indexer/src/redis/hubBalancesCache.ts
- packages/indexer/src/services/BundleBuilderService.ts
- packages/indexer/src/utils/contractUtils.ts
Adds aggregated hub balance persistence to bundle builder service for consumption in `/hubbalance` api endpoint
> feat: hubpool balance tracking and persistence

- packages/indexer-database/src/entities/evm/RequestedSpeedUpV3Deposit.ts
- packages/indexer-database/src/migrations/1729700385983-SpeedUpV3.ts
- packages/indexer/src/database/SpokePoolRepository.ts
Adding logIndex to speedup's unique constraint as there can be more than 1 event in the same transaction. See for example: https://optimistic.etherscan.io/tx/0x2b02e3132f2dba66c675be4a75de2cda2d32dea75a80123ff348d752933793d8#eventlog
> fix: speedup unique constraint

- packages/indexer-database/src/entities/evm/RequestedV3SlowFill.ts
- packages/indexer-database/src/migrations/1729701068951-SlowFillV3.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- Deleting `fromLiteChain` and `toLiteChain` columns from `requestedV3SlowFill` table as they are not populated for slow fills by the SpokePool clients.
- Changing the unique keys we are using when inserting slow fills with finalisation check as they have to match the unique constraint of the table.
> fix: slow fills insertion

- packages/indexer/src/data-indexing/service/Indexer.ts
- packages/indexer/src/generics/BaseIndexer.ts
- packages/indexer/src/main.ts
- packages/indexer/src/messaging/IntegratorIdWorker.ts
Process seemed to continue after cancelling it
This was due to worker not being stopped, so now we stop it on ctrl-c, which seems to allow app to exit cleanly
> fix(indexer): allow clean exit by stopping worker

- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/index.ts
- packages/indexer-database/src/main.ts
- packages/indexer-database/src/model/index.ts
- packages/indexer-database/src/utils/BaseRepository.ts
- packages/indexer-database/src/utils/BlockchainEventRepository.ts
- packages/indexer-database/src/utils/index.ts
- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/services/spokePoolProcessor.ts
- new [BlockchainEventRepository](https://github.com/across-protocol/indexer/pull/103/files#diff-c7565999fde564c1bde14abd561f7bd626a30813513746d1d9bd03163d7366a0) which is intended to be extended by any repository class dealing with events entities.
- [BlockchainEventRepository.saveAndHandleFinalisation()]() is a function which takes event data and performs a save operation depending on the passed `uniqueKeys` and `comparisonKeys`. The result of this save operation can be  (1) **Nothing** if the data is identical to what's stored in the database , (2) **Inserted**, if the unique keys are not present in the DB, (3) **Finalised**, if the finalised field was the only one that changed, (4) **Updated**, if any of the data fields were changed, (5) **UpdatedAndFinalised**, if both the finalised …
> fix: replace bulk upserts with inserts/updates if needed

- packages/indexer/src/services/BundleIncludedEventsService.ts
- packages/indexer/src/services/spokePoolProcessor.ts
Previously, we were querying the expired deposits and then querying its possible refunds. Now, we are getting from the database only the deposits that might be refunded based on the bundle events that are stored in the db.
This PR also fixes the bug we were having before (Cannot read properties of undefined, reading `relayerRefundRoot`). The issue was fixed by including the inner join with the bundle table when querying bundle events.
> improve(spokePoolProcessor): improved logic for setting refunded status

- Dockerfile
- packages/error-handling/.mocharc.json
- packages/error-handling/README.md
- packages/error-handling/eslint.config.js
- packages/error-handling/package.json
- packages/error-handling/src/errors/AssertError.ts
- packages/error-handling/src/errors/IndexerError.ts
- packages/error-handling/src/errors/IndexerHTTPError.ts
- packages/error-handling/src/errors/index.ts
- packages/error-handling/src/index.ts
- packages/error-handling/src/main.test.ts
- packages/error-handling/src/utils/assert.ts
- packages/error-handling/src/utils/index.ts
- packages/error-handling/src/utils/typeguards.ts
- packages/error-handling/tsconfig.json
- pnpm-lock.yaml
Initial PR to integrate a uniform data payload in the API
> feat(errors): add error class and functions

- packages/indexer-api/src/database/database.provider.ts
- packages/indexer-api/src/main.ts
- packages/indexer-database/src/utils/BaseRepository.ts
- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/HubPoolIndexerDataHandler.ts
- packages/indexer/src/data-indexing/service/Indexer.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/database.provider.ts
- packages/indexer/src/generics/BaseIndexer.ts
- packages/indexer/src/main.ts
- packages/indexer/src/services/BundleBuilderService.ts
- packages/indexer/src/services/BundleIncludedEventsService.ts
- packages/indexer/src/services/BundleServicesManager.ts
- packages/indexer/src/services/bundles.ts
- packages/indexer/src/services/spokePoolProcessor.ts
- packages/indexer/src/utils/bundleBuilderUtils.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
- packages/indexer/src/utils/contractUtils.ts
- packages/webhooks/src/notifier.ts
In order to use UMA's logger to send logs to slack, we should reduce the number of info logs in the indexer.
This PR:
- Replaces almost all info logs with debug logs
- For error-level logs, it sets the notificationPath key to "across-indexer-error" so that those are sent to a error specific channel.
- Adds the "Indexer" or "IndexerAPI" prefix to the "at" value of all logs so that we can easily filter in GCP and exclude SDK logs.
Zion PR to config slack channels: https://github.com/UMAprotocol/zion/pull/429
> chore: replace info-level logs with debug

- packages/indexer-api/src/main.ts
- packages/indexer-database/src/entities/WebhookClient.ts
- packages/indexer-database/src/migrations/1732730161339-Webhook.ts
- packages/indexer/src/main.ts
- packages/indexer/src/parseEnv.ts
- packages/webhooks/src/database/webhookClientRepository.ts
- packages/webhooks/src/eventProcessorManager.ts
- packages/webhooks/src/factory.ts
- packages/webhooks/src/types.ts
- packages/webhooks/src/utils.ts
we need an easy way to add and update arbitrary webhook clients
this adds env config var to regsiter new clients as well as removes domain checks to make it easier for testing
> feat(webhooks): allow client registration through env

- packages/indexer/src/services/bundles.ts
- packages/indexer/src/web3/constants.ts
We were making requests for blocks that were not minted yet because Aleph Zero's block time is higher that the one we had set.
+2 minor improvements.
> fix: aleph zero block time

- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer-database/src/migrations/1733247042958-RelayHashInfo.ts
This PR creates two indices for RelayHashInfo table:
- originChainId, depositId
- depositTxHash
> feat: Add depositTxHash index to RelayHashInfo table

- packages/indexer/src/data-indexing/service/HubPoolIndexerDataHandler.ts
For a bundle which block ranges are:
[21181520, 127967611, 64250084, 977154, 274166888, 48874544, 22372326, 12024812, 15683208, 8402604, 11362092, 11072547, 9674454, 22420080, 6099180]
We are seting chainIds to:
[1, 10, 137, 288, 42161, 324, 8453, 59144, 34443, 1135, 81457, 534352, 690, 7777777, 480, 41455]
But 41455 shouldn't be part of it yet.
This is causing we trying to update a spoke pool with this config
```
searchConfig: {
fromBlock: "NaN"
maxBlockLookBack: 10000
toBlock: "NaN"
}
```
Proposal chain ids are mistakenly configured every time a new chain is added.
> fix: chain ids mistakenly included in proposal entity

- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1733407862578-V3FundsDeposited.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
We want to store block timestamps with deposit data in order to calculate some metrics
This adds a column "blockTimestamp" to v3FundsDeposited, and queries per block range all the block timestamps and adds it to the data when storing in database
We will use this new value and the existing "createdAt" value, which is our insertion time, for instance:
`const depositWriteTime = toSeconds(deposit.createdAt) - deposit.blockTimestamp`
> improve(indexer): add block timestamp to depositevent data

- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
For more accurate profiling, we need to compute the time difference relatively to the time the event was inserted in the DB, not the current `now()` server timestamp at logging time.
In addition, now we profile fill events storing too
> fix: profile events storage relatively to insertion timestamp

- packages/indexer/src/web3/constants.ts
During local testing I see that the public Redstone RPC supports 10k block ranges again
> fix: revert redstone max block lookback

- packages/indexer-database/src/entities/IndexerProgressInfo.ts
- packages/indexer-database/src/entities/index.ts
- packages/indexer-database/src/main.ts
- packages/indexer-database/src/migrations/1737589453070-IndexerProgressInfo.ts
- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/Indexer.ts
There is a new `IndexerProgressInfo` entity for tracking in the SQL DB the progress for each instantiated `Indexer` class.
For each `Indexer` identifier we store: 
- `lastFinalisedBlock` The last finalised block number that has been processed by the indexer
- `latestBlockNumber` The latest onchain block number at the time of the last indexer progress info update
- `isBackfilling` Whether the indexer is still backfilling
The next step will be to move the `Indexer` from reading the `lastFinalisedBlock` value from Redis to reading it from SQL
> feat: track indexer class progress in sql

- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1737658101626-V3FundsDeposited.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/redis/redisCache.ts
- packages/indexer/src/utils/clients/SpokePoolClient.ts
- packages/indexer/src/utils/clients/index.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
- packages/indexer/src/utils/contractUtils.ts
This change removes the resolution of `quoteBlockNumber` from the spoke event indexer. It currently is not used in the context of deposit/fill lookups. This change does **not** remove the resolution of the `quoteBlockNumber` in the context of bundle creation/resolution.
Reason:
The `quoteBlockNumber` resolution in the SpokePoolClient requires a binary search to be completed from the deployment block. Since our calls are on increasing ranges and since we don't use the resolved value, we simply burn time resolving the values. 
Below is an example of the time it takes to resolve `v3FundsDeposited` which has this lookup. Note that it is 99% of the 120 seconds taken to update the spoke pool.
```
2025-01-23 16:22:15 [[34mdebug[39m]: {
"at": "SpokePoolClient",
"chainId": 1,
"message": "SpokePool …
```
> improve(performance): disable quote block lookup in spoke indexer

- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer-database/src/migrations/1737752107825-RelayHashInfo.ts
Add missing indices. Example below but over the similar ranges without cache overlap we are seeing 252ms -> 19ms. It should be noted that these ranges contain considerably less records than in the sandbox deployment so the timings are smaller in general.
```
2025-01-24 20:46:12 [[34mdebug[39m]: {
"at": "Indexer#SpokePoolProcessor#process",
"message": "System Time Log for SpokePoolProcessor#process",
"spokeChainId": 1,
"timeToAssignSpokeEvents": 0.17175000000861473,
"timeToAssignSpokeEventsToRelayHashInfo": 0.04575000001932494,
"timeToUpdateExpiredRelays": 247.56841700000223,
"timeToUpdateRefundedDeposits": 4.181042000011075,
"totalTime": 252.0016670000041,
"bot-identifier": "NO_BOT_ID",
"run-identifier": "67a618b4-0e73-4b3b-bcfd-47c045630c5a"
}
```
```
2025-01-24 20:57:57 …
```
> improve(spoke-indexer): optimize external association process

- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
The issue lies in `paginatedEventQuery` and our `maxBlockLookback`. Specifically, the utility function getPaginatedBlockRanges is causing the problem. Within this function, we floor the starting block to the nearest multiple of the maximum lookback range, ensuring that we query as much as possible within defined block ranges (snippet below). While this is efficient for long lookbacks and works well for our bots, it creates edge cases when querying smaller ranges, such as 20 blocks.
In these cases, we end up querying from `[maxLookbackFloor, toBlock]`. The issue compounds as the toBlock approaches the next boundary without crossing it, which increases the range we need to query over. Since this process is repeated for 9 parallel queries, the effect becomes more pronounced.
This behavior …
> improve(timing): reduce timing of lookback window

- packages/indexer-database/package.json
- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer-database/src/entities/evm/FilledV3Relay.ts
- packages/indexer-database/src/entities/evm/RequestedSpeedUpV3Deposit.ts
- packages/indexer-database/src/entities/evm/RequestedV3SlowFill.ts
- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/services/spokePoolProcessor.ts
- pnpm-lock.yaml
- Updating SDK to new version where depositId went from number to BigInt
- Adapting our code to this new type. The main change is that we'll be handling depositIds as a string in TypeORM entities.
> feat: handle depositId bigInt type from sdk

- packages/indexer-database/package.json
- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer-database/src/entities/evm/FilledV3Relay.ts
- packages/indexer-database/src/entities/evm/RequestedSpeedUpV3Deposit.ts
- packages/indexer-database/src/entities/evm/RequestedV3SlowFill.ts
- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/main.ts
- packages/indexer-database/src/migrations/1737650752958-DepositsUniqueConstraint.ts
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/services/spokePoolProcessor.ts
- pnpm-lock.yaml
Closes [ACX-3663](https://linear.app/uma/issue/ACX-3663/indexer-update-unique-constraints) and [ACX-3665](https://linear.app/uma/issue/ACX-3665/indexer-ensure-fill-events-are-matched-with-a-single-deposit)
This PR addresses some of the changes needed to handle duplicated deposits in the Indexer.
1. Adjust unique constraints:
- in v3FundsDeposited:  changing from `depositId` + `originChainId` to `relayHash` + `blockNumber` + `logIndex`.
- in RelayHashInfo: changing from relayHash to `relayHash` + `depositEventId`. We use `depositEventId` since deposit instances are uniquely identified in the `v3FundsDeposited` table.
2. Adjust event matching logic in relayHashInfo table:
Previously, the uniqueness of relayHash allowed us to use UPSERT queries when inserting new events. However, since …
> feat: support duplicated deposits and handle fill event matching

- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1738721858386-DepositsDeletedAt.ts
- packages/indexer-database/src/utils/BlockchainEventRepository.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/services/spokePoolProcessor.ts
With our recent update to how reorgs are handled for deposits (see [this change](https://github.com/across-protocol/indexer/pull/163/files#diff-cea1547b0947849dc19bac1c8b54d7c40a0f5975f4cba996111e8d560eab5db0L66-R68)), unfinalized events will now be stored in the `deposits` table. This PR introduces a new step in the `spokePoolIndexerDataHandler` to soft delete these events. The deleted events are then sent to the processor, where we'll update the related `relayHashInfo` records.
While updating `relayHashInfo`, we need to ensure that relations to other events (fills, slow fill requests, refunds) are not lost. The logic for handling this is as follows:
1. For each deleted deposit, retrieve the related `relayHashInfo` row. Since this is a one-to-one relation, we can be sure only one related …
> feat: handle unfinalised deposit events

- packages/indexer-database/src/entities/BundleEvent.ts
- packages/indexer-database/src/migrations/1738878727887-BundleEvents.ts
- packages/indexer/src/database/BundleRepository.ts
- packages/indexer/src/services/spokePoolProcessor.ts
Recent UMIP rule changes and duplicated deposits have introduced two new cases that the indexer must handle:
- A filler can be repaid multiple times if there are duplicate deposits matching it.
- A depositor may receive multiple refunds for a duplicate deposit if those deposits expire or are slow-filled.
To support these, we are adding the following fields to the BundleEvents table:
- eventChainId
- eventBlockNumber
- eventLogIndex
These fields will be populated using the data from the BundleDataClient and will be used to accurately match relayHashInfo records with their corresponding refunds.
> feat: support bundles with duplicated relay hashes

- packages/indexer-api/src/services/deposits.ts
We were not including the 'index' param in the cache key so it was not serving its purpose. For example, these requests:
- https://dev.indexer.api.across.to/deposit/status?depositId=1802882&originChainId=59144
- https://dev.indexer.api.across.to/deposit/status?depositId=1802882&originChainId=59144&index=1
both return:
```
{
"status": "expired",
"originChainId": 59144,
"depositId": "1802882",
"depositTxHash": "0x7e143dd28bb6dc64f22f6d5fc64b35fb67fa8387bc5d796b83818285bbbf2add",
"fillTx": null,
"destinationChainId": 34443,
"depositRefundTxHash": null,
"pagination": {
"currentIndex": 0,
"maxIndex": 1
}
}
```
> fix(api): deposit status endpoint cache key

- packages/indexer-database/src/migrations/1739385066933-DecimalPriceColumns.ts
Type was set to 'double precision' in the migrations from this PR: https://github.com/across-protocol/indexer/pull/138 but the entity type is 'decimal'. This was causing a new migration recreating the columns being created.
To fix it, we are modifying the type column from 'double precision' to 'numeric'.
> fix: price columns type

- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer/src/services/spokePoolProcessor.ts
The reference to deleted events was not being removed from relay_hash_info.
The error was that I used undefined instead of null when executing this update query:
```
await relayHashInfoRepository.update(
{ id: relatedRelayRow.id },
{ depositEventId: undefined, depositTxHash: undefined },
);
```
I'm also changing the log levels to warn and logging some details of the deleted deposit so that it's easy to debug from Slack in case that's needed.
> fix: delete reference to deleted deposits from relay hash info

- packages/indexer-database/src/migrations/1739967812685-SwapBeforeBridge.ts
We are receiving the following error when an attempt to call `pnpm run db:indexer-database:migrate:run` is made:
`QueryFailedError: column "swapBeforeBridgeEventId" of relation "relay_hash_info" already exists` 
This is a result of `packages/indexer-database/src/migrations/1739967812686-RelayHashInfo.ts` having duplicate column definitions.
> fix(migration): remove migration file due to duplicate entries

- packages/indexer/src/data-indexing/service/Indexer.ts
I've seen cases when JSON.stringify() returns an empty object `{}`. I think in these cases we can benefit from printing the raw error instance too
> fix: log error object

- packages/indexer-api/src/dtos/deposits.dto.ts
I noticed the API was unable to return the status for unsafe deposits. For example, this call:
https://dev.indexer.api.across.to/deposit/status?depositId=30566953172288618130184021794983800888451322878219651151031818372752299500678&originChainId=42161
Is returning:
```
{
"error": "DepositNotFoundException",
"message": "Deposit not found given the provided constraints"
}
```
But we do have the deposit in the database.
The issue is that superstruct parsing is truncating `depositId` as it is bigger than max int supported by js.
Right now it is parsing the params as:
```
{ depositId: 3.056695317228862e+76, originChainId: 42161, index: 0 }
```
After this change they are being parsed as:
```
{
depositId: '30566953172288618130184021794983800888451322878219651151031818372752299500678', …
```
> fix: api response for unsafe deposits

- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/data-indexing/service/constants.ts
- packages/indexer/src/redis/redisCache.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
- packages/indexer/src/web3/constants.ts
This PR:
- Adds Solana's constants.
- Adds a new `SvmSpokePoolIndexerDataHandler ` class that instantiates the svm spoke client to fetch and return events. This class will be used in other upcoming PRs.
> feat(svm): svm indexer data handler and solana constants

- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/messaging/IntegratorIdWorker.ts
- packages/indexer/src/parseEnv.ts
- packages/indexer/src/services/BundleBuilderService.ts
- packages/indexer/src/utils/bundleBuilderUtils.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
- packages/indexer/src/utils/contractUtils.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
This PR modifies the `retryProvidersFactory` so it is able to instantiate both EVM and SVM providers based on the 'family' of the provided chain. For SVM, it will instantiate cached providers.
> feat(providersFactory): support svm providers

- packages/indexer/src/web3/constants.ts
This PR speeds up the hubpool and config clients update() function by leveraging correctly the Redis cache. During my local testing, the initial update from deployment block was reduced to ~25 seconds down from 200+ seconds
> fix: reduce initial update time of hubpool and config clients

- packages/indexer-api/src/controllers/deposits.ts
- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/routers/deposits.ts
- packages/indexer-api/src/services/deposits.ts
- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1742571428156-V3DepositIndexes.ts
dart needs several new queries exposed, this is unfilled deposits
adds /deposit/unfilled with the following params:
```
export const UnfilledDepositsParams = s.object({
originChainId: s.optional(stringToInt),
destinationChainId: s.optional(stringToInt),
startTimestamp: s.optional(stringToInt),
endTimestamp: s.optional(stringToInt),
});
```
And returns a list of V3FundsDeposited
Please check that these queries look correct!
This is the original spec:
```
Unfilled deposit endpoint
The unfilled deposit endpoint should fetch a list of deposits that are yet to be filled.
Suggested endpoint: indexer.across.to/unfilled_deposits
Suggested arguments:
originChainId: Defaults to all chains
destinationChainId: Defaults to all chains
startTimestamp: Defaults to the timestamp from 5 minutes ago …
```
> feat: add unfilled deposits

- packages/indexer-api/src/controllers/deposits.ts
- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/routers/deposits.ts
- packages/indexer-api/src/services/deposits.ts
Add endpoint for dart to query recently filled deposits
This adds separate endpoint at deposits/filled, which returns deposit data + fill data for filled deposits only
This logic was not combined with unfilled because the data needed is slightly different.  i think its possible to combine all these calls but may make it a more complex than necessary
> feat: add filled deposits endpoint

- packages/indexer/src/services/BundleIncludedEventsService.ts
- packages/indexer/src/services/BundleServicesManager.ts
We add a buffer to the bundle range blocks when reconstructing it. Sometimes, after adding the buffer, we try to query a block which is greater than the latest block. This PR fixes that by capping end blocks using the lates block.
> fix: cap bundle end block

- packages/indexer-api/src/services/deposits.ts
- packages/indexer-api/src/services/fills.ts
we are seeing queries where deposits returned get skipped for some reason
This does a sort before any major filtering to make sure its return in block time order, to make results easier to reason about
> improve(api): add sorting by block time

- packages/indexer/src/parseEnv.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
We needed headers to use Matter Labs as a Lens provider, but Alchemy is now live so we don't need that anymore.
Zion PR removing envs: https://github.com/UMAprotocol/zion/pull/653
> chore: remove headers from provider set up

- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1742921797170-Deposits.ts
- packages/indexer/src/database/SpokePoolRepository.ts
To handle Solana reorgs, we’ve added `transactionHash` to the unique constraint of the deposits table, now defined as (relayHash, blockNumber, transactionHash, logIndex).
Unlike EVM chains, Solana lacks a global log index per block, so we can’t rely on logIndex alone to uniquely identify transactions. Including transactionHash ensures uniqueness, as it’s generated from transaction data and remains consistent during reorgs, even if the blockNumber (or slot) changes.
> chore: add transaction hash to deposits unique constraint

- packages/indexer/src/utils/bundleBuilderUtils.ts
We are setting the bundle start block of a new chain to 1, but we should use deployment block number instead.
This was causing issues as we try to call spoke pool functions at blocks where it was not deployed yet. See [here](https://github.com/across-protocol/sdk/blob/master/src/utils/SpokeUtils.ts#L66).
Example:
```
[error] bundle-included-events-indexer (Indexer#BundleIncludedEventsService#indexerLogic)⭢Error in BundleIncludedEventsService
• errorJson: {"reason":null,"code":"CALL_EXCEPTION","method":"getCurrentTime()",
"data":"0x","errorArgs":null,"errorName":null,"errorSignature":null,
"address":"0xe7cb3e167e7475dE1331Cf6E0CEb187654619E12","args":[],"transaction":{"data":"0x29cb924d","to":"0xe7cb3e167e7475dE1331Cf6E0CEb187654619E12"}}
• error: Error: call revert exception [ See: …
```
> fix: bundle reconstruction start block

- packages/indexer-database/src/main.ts
- packages/indexer-database/src/utils/BlockchainEventRepository.ts
- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/database/SwapBeforeBridgeRepository.ts
- packages/indexer/src/services/spokePoolProcessor.ts
This PR wraps the execution of `SpokePoolIndexerDataHandler.processBlockRange()` in a SQL transaction. In case of throwing an error, the database should be reverted to the state prior to the block range being processed.
- `fetchEventsByRange` is not included in the SQL transaction
- all queries must be executed using the new `transactionalEntityManager`
- to ensure backwards compatibility, in some functions `transactionalEntityManager` is marked as optional. In such cases the queries are executed using the `DataSource` instance
**Example:**
```javascript
const repository = transactionalEntityManager
? transactionalEntityManager.getRepository(entity)
: this.postgres.getRepository(entity);
```
- managed advisory locks `pg_advisory_xact_lock` that gets released automatically after the …
> fix: wrap spoke pool indexer in a sql transaction

- packages/indexer-database/src/entities/evm/FilledV3Relay.ts
- packages/indexer-database/src/migrations/1746458849679-FilledV3Relay.ts
- packages/indexer/src/main.ts
- packages/indexer/src/parseEnv.ts
- packages/indexer/src/services/HotfixServicesManager.ts
- packages/indexer/src/services/UnmatchedFillEventsService.ts
This PR looks for expired `relay_hash_info` records with expired status, but for which fill events exists in the raw events table
> fix: update relay hash info with unmatched fills

- packages/indexer/src/services/HotfixServicesManager.ts
We don't need to run these services that often and actually the DB queries are not very light
> fix: increase hotfix services interval

- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
This PR is part of the required changes to support Solana in the indexer. It replaces the SVMEventsClient with the SVMSpokePoolClient to query SVM events.
Upcoming PRs will store events in the database and process them using the SpokePoolProcessor.
> feat: use SVM spoke pool client to query events

- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/tests/relayHashInfo.test.ts
- packages/indexer/src/utils/adressUtils.ts
- packages/indexer/src/utils/index.ts
This PR refactors the way we format address fields. It adds a new util function that we can reuse instead of having duplicated logic for each event. That function also handles the special case where we were trying to create an SVM address from the EVM zero address which was failing in sandbox.
> fix: handle zero address when formatting

- packages/indexer-api/package.json
- packages/indexer-database/package.json
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/services/BundleBuilderService.ts
- packages/indexer/src/services/BundleIncludedEventsService.ts
- packages/indexer/src/utils/clients/SpokePoolClient.ts
- packages/indexer/src/utils/clients/index.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
- packages/indexer/src/utils/contractUtils.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
- pnpm-lock.yaml
This PR refactors the SpokePoolClient factory for it to be able to instantiate evm or svm clients.
It also introduces a custom implementation of the SVMSpokePoolClient that lets us disable block look ups in the hub pool client, same as we do for EVM.
> improve: refactor spoke pool factory to support svm

- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/services/deposits.ts
Once with supporting SVM chains, all references to EVM terminology is being deprecated for more general terms. This PR touches query parameters, caching keys and response fields.
`GET /deposit/status`
**query params**
- deprecate `depositTxHash` and add `depositTxnRef`
**response fields**
- deprecate `depositTxHash` and add `depositTxnRef`
- deprecate `fillTx` and add `fillTxnRef`
- deprecate `depositRefundTxHash` and add `depositRefundTxnRef`
---
`GET /deposit`
**query params**
- deprecate `depositTxHash` and add `depositTxnRef`
**response fields**
- deprecate `depositTxHash` and add `depositTxnRef`
- deprecate `depositRefundTxHash` and add `depositRefundTxnRef`
- deprecate `fillTx` and add `fillTxnRef`
---
`GET /deposits`
**response fields**
- deprecate `depositTxHash` and add …
> fix: rename all transactions fields to contain "txnRef"

- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/services/deposits.ts
- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1750776709049-DepositsRecipientIndex.ts
This PR adds `address` as a query param for the `/deposits` endpoint. This param enables querying transactions where the provided address is either the depositor or the recipient. This will let us keep the same behavior we had in the transactions page when using the scraper.
It also adds the required index in the recipient column of the deposits table.
> feat: new address param for deposits endpoint

- packages/indexer-api/src/services/deposits.ts
The index for `blockTimestamp` column was created for the default ascending order. This means that Postgres will store the **NULLS** at the end of the index. We can traverse the index in descending order, but in this case the **NULLS** are read **first**.
If we query data in descending order **BUT NULLS LAST**, the index is not used. This increased the response times to 2-3 minutes for the `/deposits` endpoint
> fix: fix index usage

- packages/indexer/src/database/SpokePoolRepository.ts
An incorrect slow fill request event causes overflow errors when computing the relay hash. A hot fix for this is to ignore such events for now
> fix: internal hash overflow errors

- packages/indexer/src/database/SpokePoolRepository.ts
We were parsing the relayer address to match the format of the destination chain. But since the relayer field is set to the repaymentAddress specified when calling the fill function we have to use repaymentChainId instead.
⚠️ This means we won't have the address of the actual caller of the fill function. If we want to store that too we'll have to add it in the sdk first or grab it from the transaction receipt since we are already querying it.
> fix: relayer address parsing

- packages/indexer-api/package.json
- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/services/deposits.ts
- packages/indexer-database/package.json
- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer-database/src/entities/evm/CallsFailed.ts
- packages/indexer-database/src/entities/index.ts
- packages/indexer-database/src/main.ts
- packages/indexer-database/src/migrations/1755122451833-CallsFailed.ts
- packages/indexer-database/src/migrations/1755206039812-CallsFailed.ts
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/CallsFailedRepository.ts
- packages/indexer/src/main.ts
- packages/indexer/src/services/spokePoolProcessor.ts
- packages/indexer/src/web3/EventDecoder.ts
- packages/indexer/src/web3/model/events.ts
- pnpm-lock.yaml
This PR adds tracking of CallsFailed events from MulticallHandler contracts and exposes destination action success/failure status through the API.
- Added new CallsFailed entity to store failed multicall details.
- Linked events to fills using the fill transaction receipt.
- Added a new table CallsFailed and linked events to RelayHashInfo via foreign key.
- Added includedActions flag to RelayHashInfo to mark deposits/fills with destination actions.
- Added `actionsSucceeded` field to deposit endpoints. Possible values are:
- null → no destination actions
- true → actions included and succeeded
- false → actions included but failed
> feat: index callsFailed events

- packages/indexer-api/src/services/deposits.ts
We were returning actionsSucceeded as true for unfilled deposits including a message but we should only populate that field for filled deposits.
> fix: set actionsSucceeded only after fill

- packages/indexer-database/src/entities/evm/SwapBeforeBridge.ts
- packages/indexer-database/src/migrations/1756761518537-SwapBeforeBridge.ts
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SwapBeforeBridgeRepository.ts
- packages/indexer/src/web3/EventDecoder.ts
- packages/indexer/src/web3/model/abis.ts
- packages/indexer/src/web3/model/events.ts
- pnpm-lock.yaml
In order to bump contracts repo, we had to update our implementation of the SwapBeforeBridge indexing logic.
This PR updates the indexer to keep track of both the events from the BaseSwapBeforeBridge and SpokePoolPeriphery contracts.
> fix: update swap before bridge indexing

- packages/indexer/src/data-indexing/service/constants.ts
Seeing lots of "No new blocks to index" for Lens and ZkSync. At times, we try to fetch new blocks 15 times in a minute but none have been mined. I think it's safe to reduce their indexing delay.
> chore: increase indexing delay for zksync and lens

- packages/indexer/src/services/BundleIncludedEventsService.ts
- packages/indexer/src/utils/bundleBuilderUtils.ts
This PR introduces Arweave as a fallback data source for cases where the Indexer is unable to reconstruct a bundle using on-chain data alone.
Currently, when bundle reconstruction fails, the Indexer retries indefinitely. This results in unnecessary RPC calls and no guaranteed resolution.
The proposal is to always attempt to reconstruct bundles from blockchain data first. If reconstruction fails, fall back to fetching the data from Arweave.
The tradeoff is that Arweave is not a 100% reliable data source. However, using it as a secondary option is still beneficial because:
- It prevents indefinite retries and excessive RPC consumption.
- It increases the likelihood of recovering bundles in otherwise unrecoverable cases.
- Arweave’s failure rate (returning bad or corrupted data) should be …
> feat: use arweave as fallback for failing bundles
