across-protocol/indexer

- apps/node/src/app.ts
- packages/indexer/package.json
- packages/indexer/src/main.ts
- packages/indexer/src/services/deposits.ts
- packages/indexer/src/services/index.ts
- packages/indexer/src/test/example.test.ts
- pnpm-lock.yaml
we want to index deposits and other related data
this is the start of the indexer logic which adds some basics as to how this could work. This is still a work in progress:
TODO: 
- add postgres persistenence and data types
- add cached rpc provider
- general clean up
> feat: add deposit indexer basics

- apps/node/src/app.ts
- packages/indexer-api/package.json
- packages/indexer-api/src/main.ts
- packages/indexer-api/src/services/index.ts
- packages/indexer-api/src/services/indexer.ts
- packages/indexer-database/src/entities/index.ts
- packages/indexer-database/src/index.ts
- pnpm-lock.yaml
stub out pontential api calls
hooked in deposit route to query raw deposit data. added some basic calls for mvp as well as potential future calls
add rest of data as its available in indexer in future prs
`curl localhost:8080/indexer/deposits?limit=2`
> feat: add basic indexer api

- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/services/deposits.ts
- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1727724776516-V3FundsDeposited.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- packages/indexer/src/services/spokePoolIndexer.ts
Add `integratorId` field to `v3FundsDeposited` events and `/deposits` endpoint query params.
> feat: add integrator id to deposit events

- packages/indexer/src/main.ts
This is currently set such that no other indexer runs.
> fix(indexer): run hub indexer in parallel

- .gitignore
- packages/indexer/src/main.ts
- packages/indexer/src/parseEnv.ts
- packages/indexer/src/services/HubPoolIndexerDataHandler.ts
- packages/indexer/src/services/spokePoolIndexer.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
- packages/indexer/src/utils/index.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
- packages/indexer/src/web3/constants.ts
This update introduces factory classes that streamline the process of handling environment variable parsing and configuration storage for contract clients. By internalizing these operations, it becomes easier to create new clients without needing to pass around bulky config files, simplifying the setup and reducing redundancy.
> improve(factories): contract client factories

- packages/indexer/src/web3/constants.ts
> chore: add worldchain constants

- packages/indexer-api/src/controllers/balances.ts
- packages/indexer-api/src/dtos/balances.dto.ts
- packages/indexer-api/src/services/balances.ts
- packages/indexer/src/redis/bundleLeavesCache.ts
- packages/indexer/src/services/BundleBuilderService.ts
Dependent on @daywiss's #81 endpoint. Adds spoke balance tracking.
> feat(api balance endpoint): add spoke balance API endpoint

- packages/indexer-database/src/migrations/1726249543923-ProposedRootBundle.ts
- packages/indexer-database/src/migrations/1727686818331-HubPoolFinalised.ts
- packages/indexer-database/src/migrations/1728296909794-SpokePoolFinalised.ts
fix failing migrations
mainly adds defaults where needed
> fix(database): fix some failing migrations

- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
This will make reading logs easier by not having to expand the logs to see which contract is it about
> fix: update logs

- packages/indexer-database/src/migrations/1732294733827-FinalisedEvents.ts
The EVM events entities and the migrations are out of sync so I updated DB schema. The finalised column doesn't have a default value enymore
> fix: sync migrations with events entities

- packages/indexer/src/database/SpokePoolRepository.ts
Set log level to debug to avoid sending it to Slack.
> fix: benchmark log level

- packages/indexer-database/src/entities/evm/FilledV3Relay.ts
- packages/indexer-database/src/migrations/1734957371550-FilledV3Relay.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
This PR adds timestamp to fill events
> feat: add fill event block timestamp

- packages/indexer/src/services/BundleIncludedEventsService.ts
**Problem**
In the `BundleIncludedEventsService`, I identified cases when the chain was included in the bundle, but the SpokePool contract for that chain was not deployed yet. We were trying to instantiate and update a SpokePool client with a block range at which the contract was not deployed yet. 
**Solution**
In this case, when building executed bundles, we skip the SpokePool client if the deployment block is > than the bundle end block
> fix: fix building executed bundles

- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
An introductory PR to gauge current timings on spoke indexing.
Partially closes ACX-3619
> improve(perf-test): add perf markers for spoke event indexing 

- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/Indexer.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/parseEnv.ts
- packages/indexer/src/web3/constants.ts
Changes to performance testing + optimizations. Additional context in the comments left
> improve(spoke): improve running time

- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/constants.ts
- packages/indexer/src/web3/constants.ts
- pnpm-lock.yaml
+ Support Doctor Who
+ Rename Cher constants to Soneium
> feat: support doctor who

- packages/indexer/src/messaging/priceWorker.ts
price worker is a bit noisy
change some log levels to reduce noise
> improve: change log level of some logs

- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
This PR adds a temporary `debug` log to help tracking transaction hashes for which Blast RPC returns `null` receipts
> fix: add logs for investigating null receipts

- packages/indexer/src/data-indexing/service/AcrossIndexerManager.ts
- packages/indexer/src/data-indexing/service/Indexer.ts
- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/main.ts
- packages/indexer/src/messaging/IntegratorIdWorker.ts
- packages/indexer/src/parseEnv.ts
- packages/indexer/src/services/BundleBuilderService.ts
- packages/indexer/src/utils/bundleBuilderUtils.ts
- packages/indexer/src/utils/contractFactoryUtils.ts
- packages/indexer/src/utils/contractUtils.ts
- packages/indexer/src/web3/RetryProvidersFactory.ts
This is the same as https://github.com/across-protocol/indexer/pull/218
I messed up and merged it in the wrong branch 😅
> feat(providersFactory): support svm providers

- packages/indexer-database/src/entities/RelayHashInfo.ts
- packages/indexer-database/src/migrations/1742390524038-RelayHashInfo.ts
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/messaging/priceWorker.ts
- packages/indexer/src/services/spokePoolProcessor.ts
This PR adds gas fee information about the fill transaction in the `relay_hash_info` table
> feat: add fill gas fee

- pnpm-lock.yaml
- add caching for native token prices
> feat: production release 🚀 

- packages/indexer-api/src/controllers/deposits.ts
- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/routers/deposits.ts
- packages/indexer-api/src/services/deposits.ts
- packages/indexer-database/src/entities/evm/V3FundsDeposited.ts
- packages/indexer-database/src/migrations/1742571428156-V3DepositIndexes.ts
accidently merged to master, reverted that, now merge to stage
> feat: add unfilled deposits 

- packages/indexer-api/src/controllers/fills.ts
- packages/indexer-api/src/dtos/fills.dto.ts
- packages/indexer-api/src/main.ts
- packages/indexer-api/src/routers/fills.ts
- packages/indexer-api/src/routers/index.ts
- packages/indexer-api/src/services/deposits.ts
- packages/indexer-api/src/services/fills.ts
add unmatched fills endpoint
adds a new route /fills/unmatched
"skip" is not working right for me, didnt work until i used "offset". plz look to see if that make sense
> feat(api): add unmatched fills endpoint

- packages/indexer-api/src/dtos/deposits.dto.ts
- packages/indexer-api/src/services/deposits.ts
frontend needs speedup info on deposits
This adds a secondary query to get all speedups related to the deposits returned.
> feat: add speedup array to deposits

- packages/indexer-api/src/services/deposits.ts
api calls for deposit were broken since adding new queries
Fixes a bug and split up field mappings to make sure we arent accessing unavailable props
> fix(api): fix deposit queries to correct entity and props

- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
The messages for the workers need to be published after the queries are committed, otherwise the workers won't find the data in the DB
> fix: publish messages after transaction commits

- packages/indexer-api/package.json
- packages/indexer-database/package.json
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/HubPoolIndexerDataHandler.ts
- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/utils/clients/SpokePoolClient.ts
- packages/indexer/src/utils/contractUtils.ts
- pnpm-lock.yaml
This PR prepares the indexer to run with the newest release of the SDK.
> chore: bump sdk version

- packages/indexer-api/package.json
- packages/indexer-database/package.json
- packages/indexer-database/src/entities/evm/BridgedToHubPool.ts
- packages/indexer-database/src/entities/evm/ClaimedRelayerRefunds.ts
- packages/indexer-database/src/entities/index.ts
- packages/indexer-database/src/main.ts
- packages/indexer-database/src/migrations/1749671752378-BrigdedToHubPool.ts
- packages/indexer-database/src/migrations/1749672147245-ClaimedRelayerRefund.ts
- packages/indexer/package.json
- packages/indexer/src/data-indexing/service/SpokePoolIndexerDataHandler.ts
- packages/indexer/src/data-indexing/service/SvmSpokePoolIndexerDataHandler.ts
- packages/indexer/src/database/SpokePoolRepository.ts
- pnpm-lock.yaml
This PR prepares the indexer to handle BridgedToHubPool and ClaimedRelayerRefund events.
> feat: index ClaimedRelayerRefund and BrigdedToHubPool events

- packages/indexer/src/services/BundleIncludedEventsService.ts
Reverts across-protocol/indexer#355
> Revert "fix: disable lens from bundle events service"
